defmodule FullstackChallenge.AppTemplates do
  @moduledoc """
  Contains templates for deploying basic applications to Fly.io
  """

  @doc """
  Returns a basic Nginx app configuration and files
  """
  def nginx_app_template(app_name) do
    %{
      dockerfile: dockerfile_content(),
      fly_toml: fly_toml_content(app_name),
      index_html: index_html_content(app_name),
      nginx_conf: nginx_conf_content()
    }
  end

  defp dockerfile_content do
    """
    FROM nginx:alpine
    
    COPY nginx.conf /etc/nginx/nginx.conf
    
    COPY index.html /usr/share/nginx/html/index.html
    
    EXPOSE 8080
    
    CMD ["nginx", "-g", "daemon off;"]
    """
  end

  defp fly_toml_content(app_name) do
    """
    app = "#{app_name}"
    primary_region = "sjc"

    [build]

    [http_service]
      internal_port = 8080
      force_https = true
      auto_stop_machines = "stop"
      auto_start_machines = true
      min_machines_running = 0
      processes = ["app"]

    [[vm]]
      memory = "256mb"
      cpu_kind = "shared"
      cpus = 1
    """
  end

  defp index_html_content(app_name) do
    """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>#{app_name} - Deployed with Fly.io</title>
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                margin: 0;
                padding: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                color: white;
            }
            .container {
                text-align: center;
                max-width: 600px;
                padding: 2rem;
                background: rgba(255, 255, 255, 0.1);
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
            }
            h1 {
                font-size: 3rem;
                margin-bottom: 1rem;
                font-weight: 300;
            }
            p {
                font-size: 1.2rem;
                margin-bottom: 2rem;
                opacity: 0.9;
            }
            .badge {
                display: inline-block;
                background: rgba(255, 255, 255, 0.2);
                padding: 0.5rem 1rem;
                border-radius: 25px;
                font-size: 0.9rem;
                margin: 0.25rem;
            }
            .fly-logo {
                width: 60px;
                height: 60px;
                margin: 2rem auto;
                background: white;
                border-radius: 50%;
                display: flex;
                align-items: center;
                justify-content: center;
                font-weight: bold;
                color: #333;
                font-size: 1.5rem;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="fly-logo">🚀</div>
            <h1>#{app_name}</h1>
            <p>Your app is live on Fly.io!</p>
            <div>
                <span class="badge">✅ Deployed</span>
                <span class="badge">🌍 Global Edge</span>
                <span class="badge">⚡ Fast</span>
            </div>
            <p style="margin-top: 2rem; font-size: 1rem; opacity: 0.7;">
                Generated by Fly.io Dashboard Challenge
            </p>
        </div>
    </body>
    </html>
    """
  end

  defp nginx_conf_content do
    """
    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        sendfile        on;
        keepalive_timeout  65;
        
        server {
            listen 8080;
            server_name _;
            
            root /usr/share/nginx/html;
            index index.html;
            
            location / {
                try_files $uri $uri/ =404;
            }
            
            location /health {
                return 200 "OK";
                add_header Content-Type text/plain;
            }
        }
    }
    """
  end
end